# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: leftarm
  joint_model_group_pose: leftdefault
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - head
    - leftarm_prismatic
    - leftarm_vertical_prismatic
    - leftarm_rotx
    - leftarm_rotz
    - leftforearm_prismatic
    - leftlowfinger
    - leftupfinger
    - rightarm_prismatic
    - rightarm_vertical_prismatic
    - rightarm_rotx
    - rightarm_rotz
    - rightforearm_prismatic
    - rightlowfinger
    - rightupfinger
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: leftarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - leftarm_prismatic
      - leftarm_vertical_prismatic
      - leftarm_rotx
      - leftarm_rotz
      - leftforearm_prismatic
  - name: rightarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rightarm_prismatic
      - rightarm_vertical_prismatic
      - rightarm_rotx
      - rightarm_rotz
      - rightforearm_prismatic
  - name: lefthand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - leftlowfinger
      - leftupfinger
  - name: righthand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rightlowfinger
      - rightupfinger